# Generated by Django 5.2.17 on 2026-09-28 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FonteDados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=160)),
                ('tipo', models.CharField(choices=[('api', 'API / parceria'), ('planilha', 'Planilha'), ('pdf_email', 'PDF por e-mail'), ('portal', 'Portal do corretor (RPA)'), ('upload', 'Upload manual'), ('ans', 'Dados abertos ANS')], max_length=20)),
                ('url', models.URLField(blank=True)),
                ('frequencia_esperada_dias', models.PositiveIntegerField(default=30, help_text='SLA de frescor: após esse prazo sem verificação, a fonte é marcada como atrasada.')),
                ('confiabilidade', models.PositiveSmallIntegerField(default=3, help_text='1 (baixa) a 5 (oficial/estruturada).')),
                ('responsavel', models.CharField(blank=True, max_length=120)),
                ('ultima_verificacao', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operadora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, unique=True)),
                ('registro_ans', models.CharField(blank=True, max_length=20)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoFonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/')),
                ('nome_original', models.CharField(max_length=255)),
                ('sha256', models.CharField(max_length=64, unique=True)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('recebido', 'Recebido'), ('extraido', 'Extraído'), ('erro', 'Erro na extração')], default='recebido', max_length=20)),
                ('metodo_extracao', models.CharField(blank=True, max_length=30)),
                ('mensagem_erro', models.TextField(blank=True)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='documentos', to='catalogo.fontedados')),
            ],
        ),
        migrations.AddField(
            model_name='fontedados',
            name='operadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fontes', to='catalogo.operadora'),
        ),
        migrations.CreateModel(
            name='Plano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('registro_ans', models.CharField(blank=True, max_length=30)),
                ('acomodacao', models.CharField(blank=True, choices=[('enfermaria', 'Enfermaria'), ('apartamento', 'Apartamento')], max_length=20)),
                ('operadora', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='planos', to='catalogo.operadora')),
            ],
            options={
                'unique_together': {('operadora', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(help_text='UF ou região comercial, ex.: DF', max_length=60)),
                ('tipo_contratacao', models.CharField(choices=[('PF', 'Individual/Familiar'), ('PME', 'Empresarial (PME)'), ('ADESAO', 'Coletivo por adesão')], max_length=10)),
                ('coparticipacao', models.BooleanField(default=False)),
                ('vigencia_inicio', models.DateField()),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('em_revisao', 'Em revisão'), ('publicada', 'Publicada'), ('substituida', 'Substituída'), ('rejeitada', 'Rejeitada')], default='em_revisao', max_length=20)),
                ('versao', models.PositiveIntegerField(blank=True, null=True)),
                ('pagina_origem', models.PositiveIntegerField(blank=True, null=True)),
                ('validacoes', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('revisado_por', models.CharField(blank=True, max_length=120)),
                ('revisado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao_revisao', models.TextField(blank=True)),
                ('documento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabelas', to='catalogo.documentofonte')),
                ('plano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tabelas', to='catalogo.plano')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=40)),
                ('usuario', models.CharField(blank=True, max_length=120)),
                ('detalhes', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditoria', to='catalogo.tabelapreco')),
            ],
            options={
                'ordering': ['criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ValorFaixa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa', models.PositiveSmallIntegerField(choices=[(1, '0 a 18'), (2, '19 a 23'), (3, '24 a 28'), (4, '29 a 33'), (5, '34 a 38'), (6, '39 a 43'), (7, '44 a 48'), (8, '49 a 53'), (9, '54 a 58'), (10, '59 ou mais')])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_extraido', models.DecimalField(blank=True, decimal_places=2, help_text="Valor original da extração. Diferente de 'valor' quando houve correção humana.", max_digits=10, null=True)),
                ('trecho_origem', models.CharField(blank=True, max_length=255)),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores', to='catalogo.tabelapreco')),
            ],
            options={
                'ordering': ['faixa'],
            },
        ),
        migrations.AddIndex(
            model_name='tabelapreco',
            index=models.Index(fields=['plano', 'regiao', 'tipo_contratacao', 'coparticipacao', 'status'], name='catalogo_ta_plano_i_1db0b9_idx'),
        ),
        migrations.AddIndex(
            model_name='tabelapreco',
            index=models.Index(fields=['vigencia_inicio', 'vigencia_fim'], name='catalogo_ta_vigenci_731cc6_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='valorfaixa',
            unique_together={('tabela', 'faixa')},
        ),
    ]
