# Generated by Django 5.2.17 on 2026-09-30 19:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registro_ans', models.CharField(max_length=30, unique=True)),
                ('nome', models.CharField(max_length=160)),
                ('operadora', models.CharField(blank=True, max_length=160)),
                ('contratacao', models.CharField(blank=True, max_length=40)),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('suspenso', 'Comercialização suspensa'), ('cancelado', 'Cancelado')], default='ativo', max_length=20)),
                ('situacao_desde', models.DateField(blank=True, null=True)),
                ('data_referencia', models.DateField(help_text='Data do conjunto de dados da ANS de onde veio este registro.')),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['registro_ans'],
            },
        ),
        migrations.AddField(
            model_name='documentofonte',
            name='conteudo',
            field=models.BinaryField(blank=True, help_text='Cópia do original no banco. Usada só no deploy serverless de demonstração (ORIGINAIS_NO_BANCO).', null=True),
        ),
        migrations.CreateModel(
            name='ValorComercialANS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faixa', models.PositiveSmallIntegerField(choices=[(1, '0 a 18'), (2, '19 a 23'), (3, '24 a 28'), (4, '29 a 33'), (5, '34 a 38'), (6, '39 a 43'), (7, '44 a 48'), (8, '49 a 53'), (9, '54 a 58'), (10, '59 ou mais')])),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valores_comerciais', to='catalogo.produtoans')),
            ],
            options={
                'ordering': ['faixa'],
                'unique_together': {('produto', 'faixa')},
            },
        ),
    ]
